const DUMMY_DATA = [
  // {
  //   "title": "GNU Ravish Snowboard - Womens 2022",
  //   "brand": "GNU",
  //   "gender": "womens",
  //   "size": ["152cm"],
  //   "price": "459.99",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/gnu-ravish-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freeride", "All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Hybrid", "Rocker/Camber"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Rossignol After Hours Snowboard - Womens 2022",
  //   "brand": "Rossignol",
  //   "gender": "womens",
  //   "size": ["145cm"],
  //   "price": "459.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-after-hours-snowboard-wmns-all-21-zoom.jpeg"
  //   ],
  //   "type": ["Powder", "Freeride", "All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Hybrid", "Rocker/Camber"],
  //   "flex": "Medium/Stiff",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Roxy Banana Smoothie Snowboard - Womens 2022",
  //   "brand": "Roxy",
  //   "gender": "womens",
  //   "size": ["143", "146"],
  //   "price": "459.99",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-banana-smoothie-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freeride", "All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Camber", "Rocker/Camber"],
  //   "flex": "Medium/Stiff",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "CAPiTA The Equalizer Snowboard - Womens 2022",
  //   "brand": "CAPiTA",
  //   "gender": "womens",
  //   "size": ["142", "146"],
  //   "price": "529.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/capita-the-equalizer-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freeride", "Freestyle", "All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Hybrid", "Camber/Flat(in tail)", "Rocker"],
  //   "flex": "Medium/Stiff",
  //   "width": "Regular",
  //   "featured": true,
  // },
  // {
  //   "title": "Rome Royal Snowboard - Womens 2022",
  //   "brand": "Rome Royal",
  //   "gender": "womens",
  //   "size": ["141", "144", "147"],
  //   "price": "389.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rome-royal-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["All Mountain"],
  //   "shape": "Twin",
  //   "camber": ["Hybrid"],
  //   "flex": "Soft",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Roxy XOXO Snowboard - Womens 2022",
  //   "brand": "Roxy",
  //   "gender": "womens",
  //   "size": ["139", "145", "149"],
  //   "price": "429.99",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-xoxo-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freestyle", "All Mountain"],
  //   "shape": "Twin",
  //   "camber": ["Camber"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": true,
  // },
  // {
  //   "title": "K2 Lime Lite Snowboard - Womens 2022",
  //   "brand": "K2",
  //   "gender": "womens",
  //   "size": ["153"],
  //   "price": "399.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/k2-lime-lite-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freestyle", "Park"],
  //   "shape": "Twin",
  //   "camber": ["Camber", "Camber/Rocker"],
  //   "flex": "Soft/Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Jones Flagship Snowboard - Womens 2022",
  //   "brand": "Jones",
  //   "gender": "womens",
  //   "size": ["146", "159"],
  //   "price": "649.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/jones-flagship-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freedride"],
  //   "shape": "Directional",
  //   "camber": ["Hybrid", "Camber/Rocker"],
  //   "flex": "Medium/Stiff",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "GNU Barrett Snowboard - Womens 2022",
  //   "brand": "GNU",
  //   "gender": "womens",
  //   "size": ["146", "159"],
  //   "price": "499.99",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/gnu-barrett-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Freedride", "All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Camber"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Rossignol Airis Snowboard - Womens 2022",
  //   "brand": "Rossignol",
  //   "gender": "womens",
  //   "size": ["143", "146", "149", "152"],
  //   "price": "499.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-airis-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["All Mountain"],
  //   "shape": "Directional",
  //   "camber": ["Hybrid", "Camber/Rocker"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": true,
  // },
  // {
  //   "title": "Burton Rewind Snowboard - Womens 2022",
  //   "brand": "Burton",
  //   "gender": "womens",
  //   "size": ["152"],
  //   "price": "499.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-rewind-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Park"],
  //   "shape": "Twin",
  //   "camber": ["Camber", "Camber/Flat"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Burton Talent Scout Snowboard - Womens 2022",
  //   "brand": "Burton",
  //   "gender": "womens",
  //   "size": ["152"],
  //   "price": "529.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-talent-scout-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["Park"],
  //   "shape": "Twin",
  //   "camber": ["Camber", "Camber/Flat"],
  //   "flex": "Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Burton Genie Snowboard - Womens",
  //   "brand": "Burton",
  //   "gender": "womens",
  //   "size": ["152"],
  //   "price": "287.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-genie-snowboard-wmns-19-zoom.jpeg"
  //   ],
  //   "type": ["All Mountain"],
  //   "shape": "Twin",
  //   "camber": ["Flat", "Flat/Rocker"],
  //   "flex": "Soft",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Roxy Raina Snowboard - Womens 2022",
  //   "brand": "Roxy",
  //   "gender": "womens",
  //   "size": ["143", "147", "151"],
  //   "price": "349.99",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-raina-snowboard-wmns-22-zoom.jpeg"
  //   ],
  //   "type": ["All Mountain"],
  //   "shape": "Directional Twin",
  //   "camber": ["Camber", "Camber/Rocker"],
  //   "flex": "Soft/Medium",
  //   "width": "Regular",
  //   "featured": false,
  // },
  // {
  //   "title": "Rossignol Diva LF Snowboard - Womens",
  //   "brand": "Rossignol",
  //   "gender": "womens",
  //   "size": ["144", "148"],
  //   "price": "363.95",
  //   "images": [
  //     "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-diva-lf-snowboard-wmns-all-21-zoom.jpeg"
  //   ],
  //   "type": ["Park", "All Mountain"],
  //   "shape": "Twin",
  //   "camber": ["Hybrid", "Camber/Rocker"],
  //   "flex": "Medium/Stiff",
  //   "width": "Regular",
  //   "featured": false,
  // },
  {
    "title": "GNU Pro Choice Snowboard - Womens 2022",
    "brand": "GNU",
    "gender": "womens",
    "size": ["145.5"],
    "price": "579.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/gnu-pro-choice-asym-snowboard-wmns-22-zoom.jpeg"
    ],
    "type": ["Freestyle", "All Mountain"],
    "shape": "Twin, Asymmetrical",
    "camber": ["Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Jones Mind Expander Snowboard - Womens 2022",
    "brand": "Jones",
    "gender": "womens",
    "size": ["146"],
    "price": "599.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/jones-mind-expander-snowboard-wmns-22-zoom.jpeg"
    ],
    "type": ["Powder"],
    "shape": "Directional",
    "camber": ["Rocker", "Surf/Rocker"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Rossignol Myth Snowboard - Womens",
    "brand": "Jones",
    "gender": "womens",
    "size": ["139"],
    "price": "230.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-myth-snowboard-wmns-all-21-zoom.jpeg"
    ],
    "type": ["Park", "All Mountain"],
    "shape": "Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Soft/Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Roxy XOXO Banana Snowboard - Womens",
    "brand": "Roxy",
    "gender": "womens",
    "size": ["145", "152"],
    "price": "324.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-xox-banana-wmns-snowboard-all-sizes-dark-20-zoom.jpeg"
    ],
    "type": ["Freestyle", "All Mountain"],
    "shape": "Twin",
    "camber": ["Rocker/Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Roxy Breeze Snowboard - Womens 2022",
    "brand": "Roxy",
    "gender": "womens",
    "size": ["145", "152"],
    "price": "299.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-breeze-snowboard-wmns-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional",
    "camber": ["Camber", "Rocker/Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Roxy Dawn Snowboard - Womens 2022",
    "brand": "Roxy",
    "gender": "womens",
    "size": ["142", "146", "149", "152"],
    "price": "299.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/roxy-dawn-snowboard-wmns-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Twin",
    "camber": ["Flat", "Flat/Rocker"],
    "flex": "Soft",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Burton Custom Flying V Snowboard 2022",
    "brand": "Burton",
    "gender": "mens",
    "size": ["150", "156", "158"],
    "price": "629.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-custom-flying-v-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional",
    "camber": ["Hybrid", "Rocker/Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": true,
  },
  {
    "title": "Burton Family Tree 3D Daily Driver Snowboard 2022",
    "brand": "Burton",
    "gender": "mens",
    "size": ["155", "159"],
    "price": "629.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-family-tree-3d-daily-driver-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional",
    "camber": ["Hybrid", "Rocker/Camber In Nose"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Burton Flight Attendant Wide Snowboard 2022",
    "brand": "Burton",
    "gender": "mens",
    "size": ["156", "159", "162"],
    "price": "579.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-flight-attendant-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freeride"],
    "shape": "Directional",
    "camber": ["Hybrid", "Rocker/Camber In Nose"],
    "flex": "Medium/Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Burton Free Thinker Wide Snowboard 2022",
    "brand": "Burton",
    "gender": "mens",
    "size": ["157", "160"],
    "price": "599.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-free-thinker-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Park"],
    "shape": "Twin",
    "camber": ["Camber"],
    "flex": "Medium/Stiff",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Burton Instigator Flat Top Wide Snowboard 2022",
    "brand": "Burton",
    "gender": "mens",
    "size": ["155", "165"],
    "price": "419.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/burton-instigator-flat-top-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Park"],
    "shape": "Directional",
    "camber": ["Flat", "Flat/Rocker"],
    "flex": "Medium/Stiff",
    "width": "Wide",
    "featured": true,
  },
  {
    "title": "CAPiTA Indoor Survival Snowboard 2022",
    "brand": "CAPiTA",
    "gender": "mens",
    "size": ["152"],
    "price": "549.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/capita-indoor-survival-snowboard-152-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Directional Twin",
    "camber": ["Hybrid", "Camber/Flat"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "CAPiTA Spring Break Powder Snowboard",
    "brand": "CAPiTA",
    "gender": "mens",
    "size": ["166"],
    "price": "618.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/capita-spring-break-powder-snowboard-166cm-21-zoom.jpeg"
    ],
    "type": ["Powder"],
    "shape": "Directional",
    "camber": ["Rocker", "Flat/Rocker"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "CAPiTA Navigator Snowboard 2022",
    "brand": "CAPiTA",
    "gender": "mens",
    "size": ["147", "155"],
    "price": "479.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/capita-spring-break-powder-snowboard-166cm-21-zoom.jpeg"
    ],
    "type": ["Powder", "Freeride"],
    "shape": "Directional",
    "camber": ["Hybrid"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Arbor Crosscut Camber Midwide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["165"],
    "price": "499.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-crosscut-camber-midwide-snowboard-all-21-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freeride"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Medium/Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Arbor Bryan Iguchi Pro Camber Wide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["167"],
    "price": "599.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-bryan-iguchi-pro-camber-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freeride"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Medium/Stiff",
    "width": "Wide",
    "featured": true,
  },
  {
    "title": "Arbor Foundation Midwide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["156", "159", "162"],
    "price": "329.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-foundation-midwide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Twin",
    "camber": ["Rocker"],
    "flex": "Soft/Medium",
    "width": "Midwide",
    "featured": false,
  },
  {
    "title": "Arbor Formula Rocker Midwide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["156", "159", "162"],
    "price": "379.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-formula-rocker-midwide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Twin",
    "camber": ["Rocker"],
    "flex": "Medium",
    "width": "Midwide",
    "featured": false,
  },
  {
    "title": "Arbor Annex Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["156", "162"],
    "price": "699.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-annex-snowboard-all-21-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Arbor Shiloh Camber Midwide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["160"],
    "price": "499.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-shiloh-camber-midwide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle", "Freeride"],
    "shape": "Twin",
    "camber": ["Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Arbor Coda Rocker Midwide Snowboard 2022",
    "brand": "Arbor",
    "gender": "mens",
    "size": ["157"],
    "price": "549.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/arbor-coda-rocker-midwide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Twin",
    "camber": ["Rocker"],
    "flex": "Medium/Stiff",
    "width": "Midwide",
    "featured": false,
  },
  {
    "title": "Rossignol Jibsaw Wide Snowboard 2022",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["162"],
    "price": "499.99",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-jibsaw-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Park"],
    "shape": "Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Medium",
    "width": "Wide",
    "featured": true,
  },
  {
    "title": "Rossignol Revenant Snowboard 2022",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["162", "154"],
    "price": "499.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-revenant-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Medium/Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Rossignol District Black Wide Snowboard",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["161"],
    "price": "221.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-district-black-wide-snowboard-21-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Soft/Medium",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Rossignol Juggernaut Wide Snowboard 2022",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["158", "161"],
    "price": "549.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-juggernaut-wide-snowboard-all-21-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle", "Park"],
    "shape": "Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Stiff",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Rossignol Resurgence Wide Snowboard 2022",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["155", "159", "163"],
    "price": "449.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-resurgence-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Medium",
    "width": "Wide",
    "featured": true,
  },
  {
    "title": "Rossignol One LF Wide Snowboard",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["155", "159", "163"],
    "price": "400.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-one-lf-wide-snowboard-all-21-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Medium",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Rossignol One Wide Snowboard 2022",
    "brand": "Rossignol",
    "gender": "mens",
    "size": ["155", "159", "163"],
    "price": "549.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/rossignol-one-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional Twin",
    "camber": ["Hybrid", "Camber/Rocker"],
    "flex": "Medium",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Chamonix Savoy Snowboard 2022",
    "brand": "Chamonix",
    "gender": "mens",
    "size": ["155", "159", "163"],
    "price": "259.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/chamonix-savoy-snowboard-22-zoom.jpeg"
    ],
    "type": ["Park", "Freestyle"],
    "shape": "Twin",
    "camber": ["Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": true,
  },
  {
    "title": "Chamonix Caden Snowboard 2022",
    "brand": "Chamonix",
    "gender": "mens",
    "size": ["155", "159"],
    "price": "259.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/chamonix-caden-snowbaord-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Directional Twin",
    "camber": ["Flat"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Chamonix Cornu Snowboard 2022",
    "brand": "Chamonix",
    "gender": "mens",
    "size": ["155", "159"],
    "price": "319.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/chamonix-cornu-snowbaord-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freestyle"],
    "shape": "Twin",
    "camber": ["Hybrid", "Rocker/Camber"],
    "flex": "Medium",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Nitro Slash Snowboard 2022",
    "brand": "Nitro",
    "gender": "mens",
    "size": ["156"],
    "price": "519.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/nitro-slash-snowboard-22-zoom.jpeg"
    ],
    "type": ["Powder", "Freeride"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Medium/Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Nitro Cheap Thrills Snowboard 2022",
    "brand": "Nitro",
    "gender": "mens",
    "size": ["157"],
    "price": "399.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/nitro-cheap-thrills-snowboard-22-zoom.jpeg"
    ],
    "type": ["Park"],
    "shape": "Twin",
    "camber": ["Flat"],
    "flex": "Soft/Medium",
    "width": "Regular",
    "featured": true,
  },
  {
    "title": "Nitro Team Snowboard 2022",
    "brand": "Nitro",
    "gender": "mens",
    "size": ["152", "155", "162"],
    "price": "499.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/nitro-team-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain"],
    "shape": "Directional Twin",
    "camber": ["Camber"],
    "flex": "Medium/Stiff",
    "width": "Regular",
    "featured": false,
  },
  {
    "title": "Nitro Pantera Wide Snowboard 2022",
    "brand": "Nitro",
    "gender": "mens",
    "size": ["163", "166"],
    "price": "599.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/nitro-pantera-wide-snowboard-21-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freeride"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Stiff",
    "width": "Wide",
    "featured": false,
  },
  {
    "title": "Nitro Team Blurry Face Snowboard 2022",
    "brand": "Nitro",
    "gender": "mens",
    "size": ["163", "166"],
    "price": "549.95",
    "images": [
      "https://snowboard-shop.s3.us-west-1.amazonaws.com/snowboard-img/nitro-team-pro-wide-snowboard-22-zoom.jpeg"
    ],
    "type": ["All Mountain", "Freeride"],
    "shape": "Directional",
    "camber": ["Camber"],
    "flex": "Stiff",
    "width": "Wide",
    "featured": true,
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
